[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gnumake", "gcc"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["VITE_BASE_PATH=/ npm run build"]

[start]
cmd = "node server/index.js"
