// ═══════════════════════════════════════════════════════════════════════════
//  Childcare360 — Parent Portal API  (v2.8.2)
// ═══════════════════════════════════════════════════════════════════════════
import { Router } from 'express';
import { D, uuid } from './db.js';
import { requireAuth } from './middleware.js';
const r = Router();
r.use(requireAuth);
function userEmail(u){return D().prepare('SELECT email FROM users WHERE id=?').get(u)?.email||null;}
function parentChildIds(userId){
  const email=userEmail(userId);if(!email)return[];
  const m=D().prepare("SELECT role FROM tenant_members WHERE user_id=? AND role IN ('owner','admin','director','educator','manager') LIMIT 1").get(userId);
  if(m){const t=D().prepare("SELECT DISTINCT tenant_id FROM tenant_members WHERE user_id=? AND role IN ('owner','admin','director','educator','manager')").all(userId).map(r=>r.tenant_id);if(t.length){const ph=t.map(()=>'?').join(',');return D().prepare('SELECT id as child_id FROM children WHERE tenant_id IN (' + (ph) + ') AND active=1').all(...t).map(r=>r.child_id);}}
  return D().prepare('SELECT DISTINCT child_id FROM parent_contacts WHERE email=?').all(email).map(r=>r.child_id);
}
function childTenantId(id){return D().prepare('SELECT tenant_id FROM children WHERE id=?').get(id)?.tenant_id||null;}
function sinceDate(p){if(p==='all')return'1970-01-01';const d={today:0,week:7,month:30,year:365}[p]??30;return new Date(Date.now()-d*86400000).toISOString().slice(0,10);}
r.get('/children',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.length)return res.json([]);const ph=ids.map(()=>'?').join(',');res.json(D().prepare('SELECT c.*,r.name as room_name,(SELECT COUNT(*) FROM learning_stories ls WHERE ls.tenant_id=c.tenant_id AND ls.published=1 AND ls.child_ids LIKE \'%\'||c.id||\'%\') as story_count,(SELECT COUNT(*) FROM daily_updates du WHERE du.child_id=c.id AND du.tenant_id=c.tenant_id AND du.update_date=date(\'now\',\'localtime\')) as today_update_count FROM children c LEFT JOIN rooms r ON r.id=c.room_id WHERE c.id IN (' + (ph) + ') AND c.active=1').all(...ids));}catch(e){res.status(500).json({error:e.message});}});
r.put('/children/:id',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.id))return res.status(403).json({error:'Access denied'});const{parent1_phone,parent2_phone,parent2_email}=req.body;D().prepare(`UPDATE children SET parent1_phone=COALESCE(?,parent1_phone),parent2_phone=COALESCE(?,parent2_phone),parent2_email=COALESCE(?,parent2_email),updated_at=datetime('now') WHERE id=?`).run(parent1_phone||null,parent2_phone||null,parent2_email||null,req.params.id);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
r.get('/alerts',(req,res)=>{try{const ids=parentChildIds(req.userId);const alerts=[];if(ids.length){const ph=ids.map(()=>'?').join(',');D().prepare('SELECT du.*,c.first_name FROM daily_updates du JOIN children c ON c.id=du.child_id WHERE du.child_id IN ('+ph+') AND du.category=\'incident\' AND du.update_date>=date(\'now\',\'-7 days\',\'localtime\') ORDER BY du.created_at DESC LIMIT 5').all(...ids).forEach(i=>alerts.push({severity:'urgent',title:`Incident — ${i.first_name}`,message:i.summary||i.notes||'An incident was recorded.'}));}res.json(alerts);}catch(e){res.status(500).json({error:e.message});}});
r.get('/documents/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});res.json(D().prepare(`SELECT * FROM child_documents WHERE child_id=? AND tenant_id=? AND (pending_review=0 OR pending_review IS NULL) ORDER BY created_at DESC`).all(req.params.childId,childTenantId(req.params.childId)));}catch(e){res.status(500).json({error:e.message});}});
r.get('/invoices',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.length)return res.json([]);const ph=ids.map(()=>'?').join(',');res.json(D().prepare('SELECT i.*,c.first_name,c.last_name FROM invoices i JOIN children c ON c.id=i.child_id WHERE i.child_id IN (' + (ph) + ') AND i.status!=\'draft\' ORDER BY i.created_at DESC LIMIT 30').all(...ids).map(inv=>({...inv,sessions:JSON.parse(inv.sessions||'[]')})));}catch{res.json([]);}});
r.get('/daily-updates/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});const{date=new Date().toISOString().slice(0,10)}=req.query;res.json(D().prepare(`SELECT * FROM daily_updates WHERE child_id=? AND tenant_id=? AND update_date=? ORDER BY created_at DESC`).all(req.params.childId,childTenantId(req.params.childId),date));}catch(e){res.status(500).json({error:e.message});}});
r.get('/siblings',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.length)return res.json([]);const ph=ids.map(()=>'?').join(',');res.json(D().prepare('SELECT c.*,r.name as room_name FROM children c LEFT JOIN rooms r ON r.id=c.room_id WHERE c.id IN (' + (ph) + ') AND c.active=1').all(...ids));}catch(e){res.status(500).json({error:e.message});}});
r.post('/messages',(req,res)=>{try{const{child_id,subject,body}=req.body;const user=D().prepare('SELECT email,name FROM users WHERE id=?').get(req.userId);if(!user?.email||!body)return res.status(400).json({error:'body required'});const ids=parentChildIds(req.userId);const tid_child=child_id||ids[0];if(!tid_child||!ids.includes(tid_child))return res.status(400).json({error:'No child found'});const tenantId=childTenantId(tid_child);if(!tenantId)return res.status(400).json({error:'No child found'});const id=uuid();try{D().prepare(`INSERT INTO parent_messages(id,tenant_id,child_id,parent_email,parent_name,subject,body,direction,created_at)VALUES(?,?,?,?,?,?,?,?,datetime('now'))`).run(id,tenantId,tid_child,user.email,user.name||user.email,subject||'Message from Parent',body,'inbound');}catch{D().prepare(`INSERT INTO parent_messages(id,tenant_id,child_id,parent_email,parent_name,subject,body,created_at)VALUES(?,?,?,?,?,?,?,datetime('now'))`).run(id,tenantId,tid_child,user.email,user.name||user.email,subject||'Message from Parent',body);}res.json({id,ok:true});}catch(e){res.status(500).json({error:e.message});}});
r.get('/learning/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});const since=sinceDate(req.query.period||'month');const tenantId=childTenantId(req.params.childId);const rows=D().prepare(`SELECT ls.*,u.name as educator_name FROM learning_stories ls LEFT JOIN users u ON u.id=ls.educator_id WHERE ls.tenant_id=? AND ls.published=1 AND ls.date>=? ORDER BY ls.date DESC LIMIT 50`).all(tenantId,since);res.json(rows.filter(s=>{try{return JSON.parse(s.child_ids||'[]').includes(req.params.childId);}catch{return false;}}).map(s=>({...s,child_ids:JSON.parse(s.child_ids||'[]'),eylf_outcomes:JSON.parse(s.eylf_outcomes||'[]'),tags:JSON.parse(s.tags||'[]'),photo_rows:[]})));}catch(e){res.status(500).json({error:e.message});}});
r.get('/learning/:childId/weekly-report',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});const tenantId=childTenantId(req.params.childId);const rep=D().prepare(`SELECT * FROM weekly_reports WHERE child_id=? AND tenant_id=? ORDER BY week_start DESC LIMIT 1`).get(req.params.childId,tenantId);if(!rep)return res.json(null);const stories=D().prepare(`SELECT eylf_outcomes,child_ids FROM learning_stories WHERE tenant_id=? AND published=1 AND date>=?`).all(tenantId,sinceDate('month')).filter(s=>{try{return JSON.parse(s.child_ids||'[]').includes(req.params.childId);}catch{return false;}});const counts={};stories.forEach(s=>{try{JSON.parse(s.eylf_outcomes||'[]').forEach(o=>{counts[o]=(counts[o]||0)+1;});}catch{}});const mx=Math.max(1,...Object.values(counts));const outcomes={};Object.entries(counts).forEach(([k,v])=>{outcomes[k]=Math.round((v/mx)*100);});res.json({...rep,outcomes,eylf_summary:JSON.parse(rep.eylf_summary||'{}'),progressions:JSON.parse(rep.progressions||'[]')});}catch(e){res.status(500).json({error:e.message});}});
r.get('/eylf/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});res.json(D().prepare(`SELECT * FROM child_eylf_progress WHERE child_id=? AND tenant_id=? ORDER BY eylf_outcome,sub_outcome`).all(req.params.childId,childTenantId(req.params.childId)));}catch(e){res.status(500).json({error:e.message});}});
r.get('/absences/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});res.json(D().prepare(`SELECT * FROM child_absences WHERE child_id=? AND tenant_id=? ORDER BY start_date DESC LIMIT 30`).all(req.params.childId,childTenantId(req.params.childId)));}catch{res.json([]);}});
r.post('/absences/:childId',(req,res)=>{try{const ids=parentChildIds(req.userId);if(!ids.includes(req.params.childId))return res.status(403).json({error:'Not authorised'});const{start_date,end_date,reason,notes}=req.body;if(!start_date||!reason)return res.status(400).json({error:'start_date and reason required'});const tenantId=childTenantId(req.params.childId);if(!tenantId)return res.status(400).json({error:'Child not found'});const id=uuid();try{D().prepare(`INSERT INTO child_absences(id,tenant_id,child_id,start_date,end_date,reason,notes,acknowledged,created_at)VALUES(?,?,?,?,?,?,?,0,datetime('now'))`).run(id,tenantId,req.params.childId,start_date,end_date||null,reason,notes||null);}catch{D().prepare(`CREATE TABLE IF NOT EXISTS child_absences(id TEXT PRIMARY KEY,tenant_id TEXT,child_id TEXT,start_date TEXT,end_date TEXT,reason TEXT,notes TEXT,acknowledged INTEGER DEFAULT 0,created_at TEXT DEFAULT(datetime('now')))`).run();D().prepare(`INSERT INTO child_absences(id,tenant_id,child_id,start_date,end_date,reason,notes,acknowledged)VALUES(?,?,?,?,?,?,?,0)`).run(id,tenantId,req.params.childId,start_date,end_date||null,reason,notes||null);}res.json({id,ok:true});}catch(e){res.status(500).json({error:e.message});}});
export default r;
